### PR TITLE
committing window handle to Befi branch

### PR DESCRIPTION
**Pull request by robertbob93**
Hi Befin,
I have committed window handle class. Please review and approve.

Regards,
Robert

### CODE REVIEW

**Comment by befiskaria** [comment]
> Hi Befin,
> I have committed window handle class. Please review and approve.
> 
> Regards,
> Robert

**Comment by befiskaria** [comment]
Hey Robert,
The code looks good, please add additional checks.

Regards,
Befi

**Comment by robertbob93** [comment]
Hi Befi,
I have added additional checks. Please approve.

Regards,
Robert

**Comment by befiskaria** [comment]
Hey Robert,
I have reviewed the code and it looks good. Please go ahead and merge to master branch.

Regards,
Befi

**Pull request merged**
